apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alcha-dashboard-mysql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/H-Autoever/alcha-dashboard-backend.git
    targetRevision: HEAD
    path: mysql/k8s
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
