# TimescaleDB 데이터베이스에 대한 네트워크 서비스 정의

apiVersion: v1
kind: Service
metadata:
  # 서비스 이름
  name: alcha-timescaledb
  # 네임스페이스 명시
  namespace: default
spec:
  selector:
    # 연결할 파드 선택 (StatefulSet의 라벨과 일치)
    app: alcha-timescaledb
  ports:
  - # PostgreSQL 기본 포트
    port: 5432
    # 컨테이너 포트 (실제 TimescaleDB가 실행되는 포트)
    targetPort: 5432
  # 클러스터 내부에서만 접근 가능한 서비스 타입
  type: ClusterIP

