apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alcha-timescaledb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/H-Autoever/alcha-dashboard-backend.git
    targetRevision: main
    path: timescaledb/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

