apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-immediate
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/aws-ebs
parameters:
  fsType: ext4
  type: gp2
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Delete
