apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gp3-csi-storageclass.yaml
  - alcha-timescaledb-pvc.yaml
  - alcha-timescaledb-statefulset.yaml
  - alcha-timescaledb-service.yaml
  - alcha-timescaledb-secret.yaml

